// let myDate=new Date()
// console.log(myDate)
// console.log(myDate.toString())
// console.log(myDate.toDateString())
// console.log(myDate.toLocaleDateString())
// console.log(myDate.toLocaleString())
// console.log(myDate.toJSON())

// let newDate= new Date(2023,4,15)
// console.log(newDate.toLocaleDateString())
// console.log(newDate.toDateString())

// let createdDate= new Date("01-14-2023")
//console.log(createdDate.toLocaleString())
// let newDate= Date.now()
// console.log(Math.floor(newDate/1000))
let myDate=new Date()
console.log(myDate.toLocaleString())
